const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js'),XLSX=require('../vendor/xlsx.full.min.js');
const t=s=>C.table(C.parseCSV(s));
test('CSV preserves leading zeros and quoted newlines',()=>assert.deepEqual(C.parseCSV('\ufeffid,note\r\n001,"a, b\n""quote"""\r\n'),[['id','note'],['001','a, b\n"quote"']]));
test('CSV supports semicolon/tab, empty cells and trailing delimiters',()=>{assert.deepEqual(C.parseCSV('a;b\n0;',';'),[['a','b'],['0','']]);assert.deepEqual(C.parseCSV('a\tb\n1\tfalse','\t'),[['a','b'],['1','false']]);});
test('CSV rejects broken quotes',()=>{for(const s of ['a,"broken','a,b"c','"a"x,b'])assert.throws(()=>C.parseCSV(s));});
test('CSV limits columns',()=>assert.throws(()=>C.parseCSV(Array(101).fill('a').join(',')),/columns/));
test('headers reject duplicate and empty names',()=>{assert.throws(()=>t('id,id\na,b'),/Duplicate/);assert.throws(()=>t('id,,v\na,b,c'),/empty/);});
test('header row / blank rows preserve source row numbers',()=>assert.equal(C.table([['title'],['id','v'],[],['a','x']],2).rows[0].row,4));
test('zero and false are valid values and IDs',()=>{let a=C.analyze(C.table([['id','v'],[0,false],['x',0]]),'id');assert.equal(a.issues.length,0);assert.ok(a.map.has('0'));});
test('leading zeros stay distinct',()=>assert.equal(C.compare(t('id,v\n001,a'),t('id,v\n1,a'),'id').summary.added,1));
test('duplicate IDs excluded from both sides',()=>{const r=C.compare(t('id,v\na,1\na,2\nb,3'),t('id,v\na,4\nb,3'),'id');assert.equal(r.summary.removed,0);assert.equal(r.summary.changed,0);assert.equal(r.summary.excludedKeys,1);assert.equal(r.issues.length,1);});
test('prototype-like IDs and headers work safely',()=>{let r=C.compare(t('id,__proto__\n__proto__,a'),t('id,__proto__\n__proto__,b'),'id');assert.equal(r.summary.changed,1);});
test('added removed changed unchanged and schema change',()=>{let r=C.compare(t('id,v,old\na,1,z\nb,2,z\nc,3,z'),t('id,v,new\na,9,z\nb,2,z\nd,4,z'),'id');assert.deepEqual(r.summary,{added:1,removed:1,changed:1,unchanged:1,excludedKeys:0});assert.deepEqual(r.addedColumns,['new']);assert.deepEqual(r.removedColumns,['old']);});
test('optional normalization affects keys and values',()=>{assert.equal(C.compare(t('id,v\n A ,HI'),t('id,v\na,hi'),'id',{trim:true,caseFold:true}).summary.unchanged,1);});
test('missing and duplicate normalized IDs flagged',()=>{const r=C.analyze(t('id,v\n ,a\nX,b\nx,c'),'id',{trim:true,caseFold:true});assert.deepEqual(r.issues.map(x=>x.code),['MISSING_KEY','DUPLICATE_KEY']);});
test('formulas/errors flagged; explicit formula expression comparison',()=>{const r=C.analyze(C.table([['id','v'],['a',{kind:'formula',text:'1+1'}],['b',{kind:'error',text:'#DIV/0!'}]]),'id');assert.deepEqual(r.issues.map(x=>x.code),['FORMULA','CELL_ERROR']);});
test('CSV formula injection protection and escaping',()=>{const out=C.safeCSV([['=1',' +SUM(A1)','\t@x','-1','normal','"a"']]);assert.ok(out.includes('"\'=1"'));assert.ok(out.includes('"\' +SUM(A1)"'));assert.ok(out.includes('"\'\t@x"'));assert.ok(out.includes('"\'-1"'));assert.ok(out.includes('"""a"""'));});
test('XLSX report strings do not turn into formulas',()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([[{t:'s',v:'=HYPERLINK("bad")'},{t:'s',v:'001'}]]),'Report');const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});const read=XLSX.read(bytes);assert.equal(read.Sheets.Report.A1.t,'s');assert.equal(read.Sheets.Report.A1.f,undefined);assert.equal(read.Sheets.Report.B1.v,'001');assert.ok(C.zipGuard(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength))>0);});
test('bad and inflated ZIP rejected before parser',()=>{assert.throws(()=>C.zipGuard(new Uint8Array([1,2,3,4]).buffer));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['a']]),'a');const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});const buf=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),v=new DataView(buf);for(let i=0;i<v.byteLength-46;i++)if(v.getUint32(i,true)===0x02014b50){v.setUint32(i+24,0x7fffffff,true);break;}assert.throws(()=>C.zipGuard(buf),/30 MB/);});
test('every preset has verified stable key candidates',()=>{assert.deepEqual(C.profiles.lane.keys,['deal_id','client_id','project_id','invoice_id']);assert.ok(C.profiles.proof.keys.includes('Evidence ID'));});

test('typed formulas differ from literal text and missing IDs still get formula flags',()=>{const a=C.table([['id','v'],['a',{kind:'formula',text:'1+1'}],['',{kind:'error',text:'#DIV/0!'}]]),b=C.table([['id','v'],['a','[FORMULA] 1+1']]);assert.equal(C.compare(a,b,'id').summary.changed,1);assert.deepEqual(C.analyze(a,'id').issues.map(x=>x.code),['FORMULA','MISSING_KEY','CELL_ERROR']);assert.equal(C.analyze(b,'id').issues.length,0);});

test('trailing blank XLSX header cells ignored without false extra-cell flags',()=>{const r=C.analyze(C.table([['id','v','',''],['a',1,'',''],['b',2,'extra','']]),'id');assert.equal(r.issues.length,1);assert.equal(r.issues[0].row,3);});
