'use strict';
const $=id=>document.getElementById(id), C=SheetCheck;
let language='zh',files={a:null,b:null},jobs={},report=null;
const text=(zh,en)=>language==='zh'?zh:en;
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error);}
function invalidate(){report=null;$('results').hidden=true;}
function options(s,items){s.replaceChildren(...items.map(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;return o;}));s.disabled=!items.length;}
function getTable(side){const file=files[side];if(!file)return null;return C.table(file.sheets.find(s=>s.name===$('sheet-'+side).value).rows,Number($('header-'+side).value));}
function refresh(){invalidate();try{let a=getTable('a'),b=getTable('b');let keys=a?a.headers.filter(h=>!b||b.headers.includes(h)):[];const old=$('key').value;options($('key'),keys);const preferred=C.profiles[$('profile').value].keys.find(k=>keys.includes(k));if(preferred)$('key').value=preferred;else if(keys.includes(old))$('key').value=old;$('run').disabled=!keys.length||Object.keys(jobs).length>0;if(a&&!keys.length)status(text('两表没有同名编号列。','No common column names in both sheets.'),true);else status('');}catch(e){options($('key'),[]);$('run').disabled=true;status(e.message,true);}}
function stop(side){const j=jobs[side];if(j){j.worker.terminate();clearTimeout(j.timer);delete jobs[side];} $('cancel').hidden=!Object.keys(jobs).length;}
function clearSide(side){stop(side);files[side]=null;options($('sheet-'+side),[]);$('name-'+side).textContent='—';}
function loaded(side,name,sheets){files[side]={name,sheets};$('name-'+side).textContent=name;options($('sheet-'+side),sheets.map(x=>x.name));$('header-'+side).value=1;refresh();}
async function read(side,file){clearSide(side);invalidate();refresh();if(!file)return;if(file.size>C.LIMITS.bytes){status(text('文件超过 5 MB。','File exceeds 5 MB.'),true);return;}if(!/\.(csv|xlsx)$/i.test(file.name)){status(text('只支持 XLSX 和 CSV。','Only XLSX and CSV are supported.'),true);return;}let worker;try{worker=new Worker('worker.js');}catch(e){status(text('请使用 GitHub Pages 或本地静态服务器打开。','Open through GitHub Pages or a local static server.'),true);return;}
const job={worker,timer:setTimeout(()=>{if(jobs[side]===job){stop(side);refresh();status(text('读取超时，已停止。请缩小文件。','Reading timed out and stopped. Use a smaller file.'),true);}},15000)};jobs[side]=job;$('run').disabled=true;$('cancel').hidden=false;status(text('正在本地读取，可取消…','Reading locally; you can cancel…'));
worker.onmessage=({data})=>{if(jobs[side]!==job)return;stop(side);if(data.error){refresh();status(data.error,true);}else loaded(side,file.name,data.sheets);};worker.onerror=()=>{if(jobs[side]!==job)return;stop(side);refresh();status(text('无法读取文件。请检查格式或使用较小文件。','Could not read file. Check format or use a smaller file.'),true);};try{const buffer=await file.arrayBuffer();if(jobs[side]===job)worker.postMessage({buffer,name:file.name,delimiter:$('delimiter').value==='tab'?'\t':$('delimiter').value},[buffer]);}catch(e){if(jobs[side]===job){stop(side);refresh();status(e.message,true);}}}
function reportRows(){let rows=[['Type','Source','Row','ID','Column','Before','After','Detail']];for(const x of report.issues)rows.push([x.code,x.source,x.row,x.key,x.field,'','',x.detail]);for(const x of report.changes)rows.push([x.status,'comparison',`${x.beforeRow} → ${x.afterRow}`,x.key,x.field,x.before,x.after,'']);return rows;}
function render(){if(!report)return;$('results').hidden=false;const labels={rows:['数据行','Rows'],issues:['问题','Issues'],added:['新增记录','Added records'],removed:['移除记录','Removed records'],changed:['变更记录','Changed records'],unchanged:['未变记录','Unchanged records'],excludedKeys:['排除重复编号','Excluded duplicate IDs']};$('stats').replaceChildren(...Object.entries(report.summary).map(([k,v])=>{let d=document.createElement('div');d.className='stat';let b=document.createElement('b'),s=document.createElement('span');b.textContent=v;s.textContent=text(...labels[k]);d.append(b,s);return d;}));$('schema').textContent=text('新增列：','Added columns: ')+(report.addedColumns.join(', ')||'—')+text('；移除列：','; removed columns: ')+(report.removedColumns.join(', ')||'—')+text('。只比较同名列；列变化单独记录。',' . Only shared columns are compared; schema changes are separate.');$('preview').replaceChildren(...reportRows().slice(1,101).map(r=>{const tr=document.createElement('tr');tr.append(...r.map(v=>{const td=document.createElement('td');td.textContent=C.display(v);return td;}));return tr;}));if(!report.issues.length&&!report.changes.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=8;td.textContent=text('在已检查的规则内未发现问题或变化。','No issues or changes within the checked rules.');tr.append(td);$('preview').append(tr);}}
function run(){invalidate();try{const a=getTable('a'),b=getTable('b'),key=$('key').value,opts={trim:$('trim').checked,caseFold:$('case').checked};if(!a)throw Error('Load a baseline file first');if(b){report=C.compare(a,b,key,opts);report.summary.issues=report.issues.length;}else{const r=C.analyze(a,key,opts);report={summary:{rows:r.rows,issues:r.issues.length,excludedKeys:r.duplicates.size},issues:r.issues.map(x=>({source:'before',...x})),changes:[],addedColumns:[],removedColumns:[]};}report.meta={baseline:files.a.name,snapshot:files.b?.name||'',key,trim:opts.trim,ignoreCase:opts.caseFold,baselineSheet:$('sheet-a').value,snapshotSheet:$('sheet-b').value,baselineHeader:$('header-a').value,snapshotHeader:$('header-b').value};render();status(text('检查完成。结果只覆盖所选工作表和规则。','Done. Results cover only the selected sheets and rules.'));}catch(e){status(e.message,true);}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function metadataRows(){return [['Sheet Check report',new Date().toISOString()],...Object.entries(report.meta),...Object.entries(report.summary),['Added columns',JSON.stringify(report.addedColumns)],['Removed columns',JSON.stringify(report.removedColumns)],['Limits','Values only; formula expressions compared; cached results ignored; no recalculation; shared columns only.']]};
$('xlsx').onclick=()=>{if(!report)return;try{const wb=XLSX.utils.book_new();for(const [name,rows]of [['Summary',metadataRows()],['Issues and changes',reportRows()]]){const ws=XLSX.utils.aoa_to_sheet(rows.map(r=>r.map(v=>({t:'s',v:C.display(v)}))));ws['!cols']=[{wch:25},{wch:24},{wch:15},{wch:24},{wch:24},{wch:32},{wch:32},{wch:65}];XLSX.utils.book_append_sheet(wb,ws,name);}const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'});download(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'sheet-check-report.xlsx');}catch(e){status(e.message,true);}};
$('csv').onclick=()=>{if(!report)return;download(new Blob([C.safeCSV([...reportRows(),[],['REPORT METADATA'],...metadataRows()])],{type:'text/csv;charset=utf-8'}),'sheet-check-report.csv');};
for(const side of ['a','b']){$('file-'+side).onchange=e=>read(side,e.target.files[0]);$('sheet-'+side).onchange=refresh;$('header-'+side).oninput=refresh;}$('profile').onchange=refresh;for(const id of ['key','trim','case'])$(id).onchange=invalidate;$('run').onclick=run;
$('cancel').onclick=()=>{for(const side of Object.keys(jobs))stop(side);refresh();status(text('读取已取消。','Reading cancelled.'));};
$('reset').onclick=()=>{for(const side of ['a','b']){clearSide(side);$('file-'+side).value='';$('header-'+side).value=1;}$('trim').checked=false;$('case').checked=false;refresh();status(text('文件与结果已清空。','Files and results cleared.'));};
$('demo').onclick=()=>{for(const side of ['a','b']){clearSide(side);$('file-'+side).value='';}$('profile').value='lane';loaded('a','fictional-before.csv',[{name:'CSV',rows:C.parseCSV('deal_id,deal_name,stage,est_value_usd\n001,Sample A,Qualified,800\n002,Sample B,Proposal,1200\n003,Sample C,New,300\n004,Sample D,New,500\n004,Sample duplicate,New,500\n,Sample missing,New,90')}]);loaded('b','fictional-after.csv',[{name:'CSV',rows:C.parseCSV('deal_id,deal_name,stage,est_value_usd\n001,Sample A,Won,850\n002,Sample B,Proposal,1200\n005,Sample E,New,600')}]);run();};
$('lang').onclick=()=>{language=language==='zh'?'en':'zh';document.documentElement.lang=language==='zh'?'zh-CN':'en';document.querySelectorAll('[data-zh]').forEach(el=>el.textContent=el.dataset[language]);$('lang').textContent=language==='zh'?'English':'中文';render();};
