/* Nydaymuse Sheet Check. Original code, proposed MIT license. */
(function(root){
'use strict';
const LIMITS={bytes:5*1024*1024,expanded:30*1024*1024,rows:20000,cols:100,cells:300000,sheets:30};
const profiles={generic:{label:'通用 / Generic',keys:[]},lane:{label:'Lane · 客户流程',keys:['deal_id','client_id','project_id','invoice_id']},margin:{label:'Margin · 项目收益',keys:['project_id','entry_id','expense_id','role']},crew:{label:'Crew · 交付复核',keys:['Package ID','Review ID','Requirement ID','Amount record ID']},proof:{label:'Proof · 证据记录',keys:['Case ID','Evidence ID','Version ID','Reuse ID']}};
function parseCSV(text,delimiter=','){
 text=text.replace(/^\uFEFF/,''); if(![',',';','\t'].includes(delimiter))throw Error('Unsupported delimiter');
 let rows=[],row=[],field='',quoted=false,closed=false;
 function cell(){row.push(field);field='';closed=false;if(row.length>LIMITS.cols)throw Error('Too many columns (100 maximum)');}
 function line(){cell();rows.push(row);row=[];if(rows.length>LIMITS.rows)throw Error('Too many rows (20,000 maximum)');}
 for(let i=0;i<text.length;i++){let c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else{quoted=false;closed=true;}}else field+=c;continue;}
 if(c==='"'){if(field||closed)throw Error('Invalid CSV quote');quoted=true;}else if(c===delimiter)cell();else if(c==='\r'||c==='\n'){if(c==='\r'&&text[i+1]==='\n')i++;line();}else{if(closed)throw Error('Unexpected character after CSV quote');field+=c;}}
 if(quoted)throw Error('Unclosed CSV quote');if(field||row.length||closed)line();if(rows.reduce((a,r)=>a+r.length,0)>LIMITS.cells)throw Error('Too many cells');return rows;
}
function blank(v){return v===null||v===undefined||v==='';}
function display(v){if(v&&typeof v==='object'&&v.kind)return '['+v.kind.toUpperCase()+'] '+v.text;return v===null||v===undefined?'':String(v);}
function norm(v,opts={}){if(blank(v))return '';let s=display(v);if(opts.trim)s=s.trim();if(opts.caseFold)s=s.toLocaleLowerCase('en-US');return (v&&typeof v==='object'&&v.kind?'\u0000'+v.kind+':':'')+s;}
function table(rows,headerRow=1){if(!Number.isInteger(headerRow)||headerRow<1||headerRow>rows.length)throw Error('Invalid header row');let headers=rows[headerRow-1].map(display);while(headers.length&&headers[headers.length-1]==='')headers.pop();if(!headers.length||headers.some(x=>!x.trim()))throw Error('Header names cannot be empty');if(new Set(headers).size!==headers.length)throw Error('Duplicate header names');return {headers,rows:rows.slice(headerRow).map((values,i)=>({values,row:i+headerRow+1})).filter(r=>r.values.some(v=>!blank(v)))};}
function analyze(t,key,opts={}){const k=t.headers.indexOf(key);if(k<0)throw Error('Choose a key column');let issues=[],map=new Map(),duplicates=new Set();for(const r of t.rows){if(r.values.slice(t.headers.length).some(v=>!blank(v)))issues.push({row:r.row,key:'',field:'',code:'EXTRA_CELLS',detail:'Cells beyond header width'});const id=norm(r.values[k],opts);if(!id){issues.push({row:r.row,key:'',field:key,code:'MISSING_KEY',detail:'Empty key (after chosen normalization)'});}else if(map.has(id)){duplicates.add(id);issues.push({row:r.row,key:id,field:key,code:'DUPLICATE_KEY',detail:'Duplicate key; excluded from comparison'});}else map.set(id,r);for(let i=0;i<t.headers.length;i++){const v=r.values[i];if(v&&typeof v==='object'&&v.kind==='formula')issues.push({row:r.row,key:id,field:t.headers[i],code:'FORMULA',detail:'Formula expression only; cached value ignored, not recalculated'});if(v&&typeof v==='object'&&v.kind==='error')issues.push({row:r.row,key:id,field:t.headers[i],code:'CELL_ERROR',detail:display(v)});}}
 for(const id of duplicates)map.delete(id);return {issues,map,duplicates,rows:t.rows.length};}
function compare(before,after,key,opts={}){const a=analyze(before,key,opts),b=analyze(after,key,opts),blocked=new Set([...a.duplicates,...b.duplicates]);let changes=[];const common=before.headers.filter(h=>after.headers.includes(h));let summary={added:0,removed:0,changed:0,unchanged:0,excludedKeys:blocked.size};for(const [id,r]of a.map){if(blocked.has(id))continue;if(!b.map.has(id)){summary.removed++;changes.push({status:'REMOVED',key:id,field:'',before:JSON.stringify(r.values),after:'',beforeRow:r.row,afterRow:''});continue;}const s=b.map.get(id);let changed=false;for(const h of common){const av=r.values[before.headers.indexOf(h)],bv=s.values[after.headers.indexOf(h)];if(norm(av,opts)!==norm(bv,opts)){changed=true;changes.push({status:'CHANGED',key:id,field:h,before:display(av),after:display(bv),beforeRow:r.row,afterRow:s.row});}}summary[changed?'changed':'unchanged']++;}for(const [id,r]of b.map){if(!a.map.has(id)&&!blocked.has(id)){summary.added++;changes.push({status:'ADDED',key:id,field:'',before:'',after:JSON.stringify(r.values),beforeRow:'',afterRow:r.row});}}return {summary,changes,issues:[...a.issues.map(x=>({source:'before',...x})),...b.issues.map(x=>({source:'after',...x}))],addedColumns:after.headers.filter(h=>!before.headers.includes(h)),removedColumns:before.headers.filter(h=>!after.headers.includes(h))};}
function safeCSV(rows){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=display(v);if(/^[\s\u0000-\u001f]*[=+@-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
function zipGuard(buffer){const u=new Uint8Array(buffer),v=new DataView(buffer);if(u[0]!==80||u[1]!==75)throw Error('Not a valid XLSX ZIP file');let e=-1;for(let i=u.length-22;i>=Math.max(0,u.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){e=i;break;}if(e<0)throw Error('Invalid ZIP directory');let n=v.getUint16(e+10,true),p=v.getUint32(e+16,true),total=0;if(n>1000||n===65535)throw Error('Workbook ZIP exceeds limits');for(let i=0;i<n;i++){if(p+46>u.length||v.getUint32(p,true)!==0x02014b50)throw Error('Invalid ZIP directory entry');if(v.getUint16(p+8,true)&1)throw Error('Encrypted ZIP unsupported');let size=v.getUint32(p+24,true);total+=size;if(total>LIMITS.expanded||size===0xffffffff)throw Error('Expanded workbook exceeds 30 MB limit');p+=46+v.getUint16(p+28,true)+v.getUint16(p+30,true)+v.getUint16(p+32,true);}return total;}
const api={LIMITS,profiles,parseCSV,blank,display,norm,table,analyze,compare,safeCSV,zipGuard};if(typeof module!=='undefined')module.exports=api;else root.SheetCheck=api;
})(globalThis);
